// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApd_yNiNBF9WRFCZJk4YzLehTKYDSuWug',
    appId: '1:33259144713:web:865acfa7b74ed76a589ad8',
    messagingSenderId: '33259144713',
    projectId: 'monly-a7092',
    authDomain: 'monly-a7092.firebaseapp.com',
    storageBucket: 'monly-a7092.firebasestorage.app',
    measurementId: 'G-MM2F8NH2GV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-mAVXEQVccWYmTreYBD29rUKBJXFYk-c',
    appId: '1:33259144713:android:e7173fdfea4dd9a7589ad8',
    messagingSenderId: '33259144713',
    projectId: 'monly-a7092',
    storageBucket: 'monly-a7092.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlfY93OhwaM1A1hgR_gP5v1Tgo7F5tUvY',
    appId: '1:33259144713:ios:03e4e40b11e2b847589ad8',
    messagingSenderId: '33259144713',
    projectId: 'monly-a7092',
    storageBucket: 'monly-a7092.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlfY93OhwaM1A1hgR_gP5v1Tgo7F5tUvY',
    appId: '1:33259144713:ios:03e4e40b11e2b847589ad8',
    messagingSenderId: '33259144713',
    projectId: 'monly-a7092',
    storageBucket: 'monly-a7092.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApd_yNiNBF9WRFCZJk4YzLehTKYDSuWug',
    appId: '1:33259144713:web:083fba1bbc4dbeb1589ad8',
    messagingSenderId: '33259144713',
    projectId: 'monly-a7092',
    authDomain: 'monly-a7092.firebaseapp.com',
    storageBucket: 'monly-a7092.firebasestorage.app',
    measurementId: 'G-JCRP2TF5ZW',
  );

}